### ISSUE TITLE
Ways to contact you 

### ISSUE THREAD

**Issue by Applebois** [dfirpaul/myfiles#1]
Hi Sorry for opening an issues on your repository.

I actually came across your profile and you have fork the OSEP Respostiory and would like to request your help to remove from your end. 

https://github.com/dfirpaul/OSEP

Thank you the help in advanced.

Anything can drop me an email `me@tehwinsam.com`

**Comment by Applebois** [comment]
@dfirpaul  please look into this issue urgent and thanks

**Comment by Dviros** [comment]
@dfirpaul Your help is required. Please assist.
Thank you.
